default_install_hook_types: [commit-msg, pre-commit]
default_stages: [pre-commit, manual]
fail_fast: true
repos:
  - repo: local
    hooks:
      - id: commitizen
        name: "git · Validate commit message"
        entry: cz check
        args: [--commit-msg-file]
        require_serial: true
        language: system
        stages: [commit-msg]
      - id: uv-lock-check
        name: "uv · Validate lock file"
        entry: uv lock
        args: ["--check"]
        require_serial: true
        language: system
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        name: "Checker · check-yaml"
      - id: check-toml
        name: "Checker · check-toml"
      - id: end-of-file-fixer
        name: "Fixer · end-of-file-fixer"
      - id: trailing-whitespace
        name: "Fixer · trailing-whitespace"
