name: PR

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest

    name: Check PR title

    steps:
      - name: Set up uv
        uses: astral-sh/setup-uv@v7

      - name: Check PR title
        run: |
          uvx --from=commitizen cz check --message "${{ github.event.pull_request.title }}"

  run-tests:
    name: Run pytest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Sync dependencies (dev)
        run: |
          uv sync --locked --all-extras --dev

      - name: Run pytest
        run: |
          # Generate a JUnit report for debugging (optional)
          mkdir -p reports
          uv run pytest -v --ctrf ./reports/pytest-ctrf.json

      - name: Publish Test Reports
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './reports/pytest-ctrf.json'
          pull-request-report: true
          github-report: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
