on:
  push:
    branches:
      - master

permissions: read-all

name: release-please

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      pr: ${{ steps.release.outputs.pr }}
      sha: ${{ steps.release.outputs.sha }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json

  update-uv-lock:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.pr }}
    steps:
      - uses: actions/checkout@v6
        with:
          # We must check out the branch created by release-please
          ref: ${{ fromJson(needs.release-please.outputs.pr).headBranchName }}
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Update uv.lock
        run: |
          uv lock

      - name: Configure git as github-actions[bot]
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit uv.lock
        uses: devops-infra/action-commit-push@v1.0.3
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_prefix: "chore: "
          commit_message: "update uv.lock"

  label-associated-pr:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - uses: jwalton/gh-find-current-pr@master
        id: prs-for-commit
        with:
          sha: ${{ needs.release-please.outputs.sha }}
          state: all

      - name: Add label to PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ fromJSON(steps.prs-for-commit.outputs.numbers)[0] }}
          labels: "autorelease: published"

      - name: Remove label from PR
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ fromJSON(steps.prs-for-commit.outputs.numbers)[0] }}
          labels: "autorelease: tagged"
